# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-26 14:02
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='colegio',
            field=otree.db.models.StringField(choices=[('San Pedro', 'San Pedro'), ('San Jose', 'San Jose'), ('Nstra Señora Rosario', 'Nstra Señora Rosario'), ('Colegio4', 'Colegio4')], max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='curso',
            field=otree.db.models.StringField(choices=[('8a', '8a'), ('8b', '8b'), ('8c', '8c'), ('9a', '9a'), ('9b', '9b'), ('9c', '9c'), ('10a', '10a'), ('10b', '10b'), ('10c', '10c')], max_length=10000, null=True),
        ),
    ]
